### ISSUE TITLE
Where can I find the payload source?

### ISSUE THREAD

**Issue by thomaskonrad** [federicodotta/Java-Deserialization-Scanner#1]
Hi Frederico,

sorry that I make this an issue - I wasn't able to find your contact details. I found a vulnerable service during a penetration test using your plugin - I wanted to ask you where I can find the source code of the test payloads? I would like to create a proof-of-concept exploit for the customer.

You say in the description that you expanded on the ysoserial test payloads - how exactly did you do that?

Thanks
Thomas

**Comment by federicodotta** [comment]
Hi Thomas,

ysoserial generate payload that execute commands on the system, using Java exec method. The best method I found for a reliable detection is to use Java native sleep. In order to generate payloads based on Java native sleep, I have modified the chains of ysoserial in order to execute, if possibile, a Thread.sleep instead of a Runtime.exec.

In the source code of my plugin there are the payload generated with my version of ysoserial encoded in Base64. You can find my version of ysoserial in my GitHub repository.

Soon I will release a new version of the plugin with a explotation tab that use frohoff ysoserial for the generation of the exploitation payloads.
