### ISSUE TITLE
Error when exploiting - lack of Java 8 support?

### ISSUE THREAD

**Issue by engn33r** [federicodotta/Java-Deserialization-Scanner#21]
Does anyone else have this error when using the latest Burp release, 2020.4, on Windows? After clicking the "Attack" button in the "Exploiting" tab, I encountered the below error message:

```
Error while generating or serializing payload
com.nqzero.permit.Permit$InitializationFailed: initialization failed, perhaps you're running with a security manager
	at com.nqzero.permit.Permit.setAccessible(Permit.java:22)
	at ysoserial.payloads.util.Reflections.setAccessible(Reflections.java:17)
	at ysoserial.payloads.util.Reflections.getFirstCtor(Reflections.java:45)
	at ysoserial.payloads.util.Gadgets.createMemoizedInvocationHandler(Gadgets.java:72)
	at ysoserial.payloads.util.Gadgets.createMemoitizedProxy(Gadgets.java:67)
	at ysoserial.payloads.CommonsCollections1.getObject(CommonsCollections1.java:148)
	at ysoserial.payloads.CommonsCollections1.getObject(CommonsCollections1.java:43)
	at ysoserial.GeneratePayload.main(GeneratePayload.java:59)
Caused by: com.nqzero.permit.Permit$FieldNotFound: field "override" not found
	at com.nqzero.permit.Permit.<init>(Permit.java:222)
	at com.nqzero.permit.Permit.build(Permit.java:117)
	at com.nqzero.permit.Permit.<clinit>(Permit.java:16)
	... 7 more
```

I found this is already an open issue for the ysoserial project and can be fixed by using Java 8: (https://github.com/frohoff/ysoserial/issues/136)

I did not use this extension before upgrading to the latest Burp Suite release, but the release notes state that Java 8 is no longer supported: https://portswigger.net/burp/releases/professional-community-2020-4

If other users encounter this error when running the latest Burp release, perhaps we must wait until ysoserial supporting newer Java versions.

**Comment by absane** [comment]
Yep. I am running into this now. Unfortunately the client I am testing an app for requires I test within their VM, so my options are limited as far as what I can do to correct this.

**Comment by engn33r** [comment]
Seeing as I am not alone in experiencing this issue, I posted to Burp's user forum to gather additional input: https://forum.portswigger.net/thread/latest-burp-upgrade-breaking-ysoserial-integration-d06fb4b0

The only workaround I have for now is using ysoserial on its own with Java 8, without Burp integration.

**Comment by federicodotta** [comment]
Hi @engn33r 

The issue is probably caused by security measures enabled by default in the last versions of Java.

Java Deserialization Scanner has all the detection payloads hardcoded in the plugin and consequently the plugin should work well with all Java version (for the detection part).

Taking into account exploitation, the plugin simply executes ysoserial with "java -jar" and consequently the payload generation fails with last Java versions. I will modify the code of the plugin in order to let the user choose the full java command for ysoserial, allowing you to disable Java protections or to use a custom Java version, also different from the one used by Burp Suite.

Federico

**Comment by federicodotta** [comment]
Hi @engn33r, 

with version 0.7 you can now add in the Configuration tab the path of a java version that works with ysoserial.

Sorry for the delay.

Federico

**Comment by engn33r** [comment]
Thank you for the upgrade!
