### ISSUE TITLE
Question about Burp and the latest version of the extension

### ISSUE THREAD

**Issue by halfluke** [federicodotta/Java-Deserialization-Scanner#22]
Hi,
just a couple of doubts:

- why does Burp BAPP Store say you need Burp Pro for this extension, when I was able to download it and add the jar manually, and it seems to work?
- why does the extension say version 0.5 (in the "Show in UI" output in Burp, when I load it), when it should be 0.6? Just a typo?

Cheers.

**Comment by federicodotta** [comment]
Hi @halfluke,

the version is a typo. I will release another version with a fix to the exploitation tab and the version fixed in a few days. Thank you.
 
About the "Pro extension", it is Burp Suite that labels the extensions as Pro, but I if I'm not wrong you can manually add the jar of all the Pro extensions also in the Community Edition (and all the extensions can be freely downloaded from the GitHub repositories of the authors or from Burp Suite GitHub repository). I think that they label my extensions as "Pro" because it adds some checks to the Active Scanner tool and the scanner is not present in the Community Edition.

Cheers

**Comment by halfluke** [comment]
Thanks / Grazie Federico!
