### ISSUE TITLE
Different results with different payload encode method

### ISSUE THREAD

**Issue by junzi749** [federicodotta/Java-Deserialization-Scanner#3]
Hi,

When we choose different payload encode methods, the results give us a different result.

If we choose "Attack(Base64)" or "Attack(Ascii Hex)", it will show "Apache Commons Collections 3 Alternate payload 2: NOT vulnerable."

However, if we choose "Attack", the result will show "Apache Commons Collections 3 Alternate payload 2: **Potentially VULNERABLE!!!**"

Does it indicate a false positive?

In addition, if convenient, could you tell how you generate this default payload? Is it using Commons Collections 5?

Thank you very much.

**Comment by federicodotta** [comment]
Hi junzi749,

It is correct to have a different results on different encodings. If you have a server application that takes serialized Java objects encoded in Base64 you have to choose "Attack (Base64)", if the server takes serialized Java object encoded in Ascii Hex you have to choose "Attack (Ascii Hex)" and if the server takes serialized Java object not encoded (in binary form) you have to choose "Attack". Usually the server expects the objects in one format and if you choose the wrong encoding it discard the requests.

In your situation, you can assume:
1) The server application is vulnerable and it handles serialized Java object not encoded
2) OR it may be a false positive

My scanner payload executes a Thread.sleep(10) on the server and uses time to check the presence of the issue. To verify if the issue is present, you can install a plugin that logs the requests (like "Logger++" from the BAppStore) and send the request that potentially trigger the issue to the repeater. Than, if the time of the request is like 10 seconds or more, it is probably that the issue is present (and you can use the "Exploiting" tab if you need). 

Alternatively, you can enable "Verbose mode" (from the "Configurations" pane) and repeat the "Attack". With this mode the tool logs requests and responses and from the response sometimes you can understand if the attack was successfull or not.

The payload triggers a vulnerability in Apache Commons Collections 3 (not 5). There are also payloads for Apache Commons Collections 4. I generated it with a modified version of ysoserial that executes the "Thread.sleep" insted of the "Runtime.exec". The "Runtime.exec" is usefull for exploitation, but it is not the best for the detection.

If you have other questions, I'm here!
